abstract final class AppRouteNames {
  static const home = 'home';
  static const discover = 'discover';
  static const discoveryDirectory = 'discovery-directory';
  static const collection = 'collection';
  static const rankings = 'rankings';
  static const library = 'library';
  static const profile = 'profile';
  static const account = 'account';
  static const appearanceSettings = 'appearance-settings';
  static const playbackSettings = 'playback-settings';
  static const contentSettings = 'content-settings';
  static const downloadSettings = 'download-settings';
  static const downloadManagement = 'download-management';
  static const privacySettings = 'privacy-settings';
  static const appSettings = 'app-settings';
  static const helpFeedback = 'help-feedback';
  static const diagnostics = 'diagnostics';
  static const update = 'update';
  static const about = 'about';
  static const search = 'search';
  static const video = 'video';
  static const playlist = 'playlist';
  static const subscription = 'subscription';
}
